SELECT
  id_nbr as key,
  first_name,
  last_name,
  gender,
  race_ethnicity_cd,
  race_ethnicity_desc,
  birth_year,
  high_degree_cd,
  high_degree_desc,
  school_year as year,
  contract_days,
  local_exp,
  total_exp,
  salary,
  salary_nominal,
  benefits,
  benefits_nominal,
  hire_agency_type_cd,
  hire_agency_type_desc,
  work_agency_type_cd,
  work_agency_type_desc,
  hire_agency_cd,
  hire_agency_desc,
  work_agency_cd,
  work_agency_desc,
  school_cd,
  school_name,
  assignment_area_cd,
  assignment_area_description,
  low_grade,
  high_grade,
  bilingual,
  assign_fte as assignment_fte,
  school_level_cd,
  school_level_desc,
  cesa_num,
  county_number as county_num,
  county_name,
  school_mailing_address1,
  mail_city,
  mail_st,
  mail_zip_cd,
  long_term_sub,
  sub_contracted
FROM
  `wi-dpi-010.2015.2015_Real`
UNION ALL
SELECT
  id_nbr as key,
  first_name,
  last_name,
  gender,
  race_ethnicity_cd,
  race_ethnicity_desc,
  birth_year,
  high_degree_cd,
  high_degree_desc,
  school_year as year,
  contract_days,
  local_exp,
  total_exp,
  salary,
  salary_nominal,
  benefits,
  benefits_nominal,
  hire_agency_type_cd,
  hire_agency_type_desc,
  work_agency_type_cd,
  work_agency_type_desc,
  hire_agency_cd,
  hire_agency_desc,
  work_agency_cd,
  work_agency_desc,
  school_cd,
  school_name,
  assignment_area_cd,
  assignment_area_description as assignment_area_desc,
  low_grade,
  high_grade,
  bilingual,
  assign_fte as assignment_fte,
  school_level_cd,
  school_level_desc,
  cesa_num,
  county_number as county_num,
  county_name,
  school_mailing_address1,
  mail_city,
  mail_st,
  mail_zip_cd,
  long_term_sub,
  sub_contracted
FROM
  `wi-dpi-010.2016.2016_Real`
UNION ALL

